name: E2E on Chrome
on:
  push:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm install
      - name: Run test
        run: npm run test
      - name: Merge test report
        run: npm run test:merge-report
      - name: Genereate report as Html
        run: npm run test:genereate-report
      - name: Copy test to public dir
        run: |
          mkdir public
          cp -r cypress/results/* public
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tester-report"
          heroku_email: "aekachai.b@20scoops.net"
        env:
          CI: true
